#include "pch.h"
#include "Parameter.h"

Parameter::Parameter()
	: m_imageBitCount(8)
	, m_imageSizeX(23428)
	, m_imageSizeY(10200)
	, m_saveImageCount(30)
	, m_px2mm(0.054) //m_px2mm(0.073)
	, m_FWHM_IncStep_mm(0.20)
	, m_FWHM_IncStepCount(29)
	, m_illuminationIncidence_theta_degree(40.)
	, m_illuminationIncidence_phi_degree(0.)
	, m_illuminationIntensity_gv(0x0001 << (m_imageBitCount - 2))
	, m_illuminationGratingPitch_mm(0.44)
	, m_illuminationGratingPhaseOffset_deg(0.)
	, m_backgroundShape_xx(0.0005)
	, m_backgroundShape_xy(0.)
	, m_backgroundShape_yy(0.001)
	, m_backgroundShape_x(0.)
	, m_backgroundShape_y(0.)
	, m_backgroundShape_z0(0.)
	, m_gaussainShapePositionX_mm(0.)
	, m_gaussainShapePositionY_mm(0.)
	, m_gaussianShapeDepth_mm(0.015)
	, m_gaussianShapeFWHM_mm(0.75)
	, m_surfaceNormalRandomLimitX_degree(10.)
	, m_surfaceNormalRandomLimitY_degree(10.)
	, m_reflectionDistribution_rad(10.)
	, m_pointSpreadFunctionSigma(0.85)
	, m_pointSpreadFunctionKernelSize(7)
	, m_modulationIntensityOffset_gv(200)
	, m_poissonNoiseLimit_ratio(2)
	, m_gaussianNoiseSigma_gv(10.)
	, m_fft_1D(FALSE)
	, m_fft_boundaryMirroring(TRUE)
	, m_fft_useHanningWindow(TRUE)
	, m_fft_carrierFrequencyX(530)
	, m_fft_frequencyBandWidthX(250)
	, m_fft_frequencyBandWidthY(500)
	, m_fft_butterworthFilterOrder(3)
	, m_loadVerticalFringeImage(TRUE)
	, m_fft_fringeReconstructionGain(5)
{

}